sources:
  source1:
    source_type: random
    port: 5554
    frequency: 0.05
    ml_model: SKlearnIsolatedForest
    data_mode: default
    serialization: json
    batch_size: 40
    verbose: true

  source2:
    source_type: outlier
    port: 5556
    frequency: 0.05
    ml_model: SKlearnIsolatedForest
    data_mode: default
    serialization: json
    batch_size: 40
    verbose: false

  source3:
    source_type: outlier
    port: 5557
    frequency: 0.1
    ml_model: SKlearnIsolatedForest
    data_mode: default
    serialization: json
    batch_size: 40
    verbose: false

  source4:
    source_type: random
    port: 5558
    frequency: 0.1
    ml_model: SKlearnIsolatedForest
    data_mode: default
    serialization: json
    batch_size: 20
    verbose: false